/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca_management;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.driver.*;
import oracle.sql.*;

/**
 *
 * @author sonal
 */
public class Display_Bills extends javax.swing.JFrame {
String c_name,gst_no,pan_no,c_phone,c_addr,bill_no,bill_pre,details_of_services,particulars,amount,name,date1;
//int bill_no1;
 //public static final String DATE_FORMAT_NOW = "dd.MM.yy";
    Statement stmt;
    /**
     * Creates new form Display_Bills
     */
    public Display_Bills() {
         try
        {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            System.out.println("Connecting....");
            Connection conn= DriverManager.getConnection("jdbc:oracle:thin:system/system@localhost:1521:XE","system","system");
            System.out.println("Connected successfully....");
            stmt = conn.createStatement();
           //stmt1 = conn.createStatement();
        }
        catch(Exception e)
        {}
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("DISPLAY CLIENT");

        jButton4.setText("LOGOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BILL NO", "CLIENT NAME", "BILL DATE", "GST NO", "PAN NO", "DETAIL OF SERVICES", "PARTICULARS", "AMOUNT", "BILL PREFIX", "NAME NO SIGNATORY", "CLIENT PHONE NO", "CLIENT ADDRESSl"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setColumnSelectionAllowed(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton2.setText("DISPLAY ALL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(391, 391, 391)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(506, 506, 506)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Bills().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new lOGoUT().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        // TODO add your handling code here:

        //ArrayList columnNames = new ArrayList();
        // ArrayList data = new ArrayList();

        String s = "SELECT b.bill_no,c.c_name,b.date1,c.gst_no,c.pan_no,b.details_of_service,b.particulars,b.amount,b.bill_pre,b.name,c.c_phone,c.c_addr from bill  b , client  c where b.c_name =c.c_name";
        //String s1;
        System.out.println(s);
        try {
            ResultSet rs1 = stmt.executeQuery(s);
            System.out.println("query executed");
            while(rs1.next()) {
                bill_no = rs1.getString(1);
                c_name = rs1.getString(2);
               date1= rs1.getString(3);
                gst_no = rs1.getString(4);
                pan_no=rs1.getString(5);
                
                details_of_services=rs1.getString(6);
                particulars=rs1.getString(7);
                amount=rs1.getString(8);
                bill_pre=rs1.getString(9);
                name=rs1.getString(10);
                c_phone=rs1.getString(11);
                c_addr=rs1.getString(12);
                
                
                //     while (rs.next())
                //  {

                    //  ArrayList row = new ArrayList(4);

                    //    for (int i = 1; i <= 4; i++)
                    //    {
                        //        row.add( rs.getObject(i) );
                        //    }

                    //    data.add( row );
                    //       }

                Object[] row = { bill_no,c_name,date1,gst_no,pan_no,details_of_services,particulars,amount,bill_pre,name,c_phone,c_addr };
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

                model.addRow(row);
                // JTable.setdata, columnNames);

            // String s = cust_id+"\t"+fname+"\t"+lname+"\t"+city+"\t"+pincode+"\t"+phone1+"\t"+phone2+"\t"+trans_id+"\t";
            //  jTextArea1.append(s+"\n");
        }

        } catch(Exception e) {
            System.out.println("Exception = "+e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

 int row=jTable2.getSelectedRow();
        //int col=jTable2.getSelectedRow();
        String p=jTable2.getModel().getValueAt(row, 0).toString();
        String p1=jTable2.getModel().getValueAt(row, 1).toString();
        String p2=jTable2.getModel().getValueAt(row, 2).toString();
        String p3=jTable2.getModel().getValueAt(row, 3).toString();
        String p4=jTable2.getModel().getValueAt(row, 4).toString();
        String p5=jTable2.getModel().getValueAt(row, 5).toString();
        String p6=jTable2.getModel().getValueAt(row, 6).toString();
        String p7=jTable2.getModel().getValueAt(row, 7).toString();
        String p8=jTable2.getModel().getValueAt(row, 8).toString();
        String p9=jTable2.getModel().getValueAt(row, 9).toString();
        String p10=jTable2.getModel().getValueAt(row, 10).toString();
        String p11=jTable2.getModel().getValueAt(row, 11).toString();
        //System.out.println();
        new Bill_Details(p,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11).setVisible(true);

        

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display_Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display_Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display_Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display_Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display_Bills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
