/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca_management;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.driver.*;
import oracle.sql.*;

/**
 *
 * @author sonal
 */
public class Search_Bill extends javax.swing.JFrame {
String c_name,gst_no,pan_no,c_phone,c_addr,bill_no,bill_pre,details_of_services,particulars,amount,name,date1;
//int bill_no1;
 //public static final String DATE_FORMAT_NOW = "dd.MM.yy";
    Statement stmt,stmt1;
    /**
     * Creates new form Search_Bill
     */
    public Search_Bill() {
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            System.out.println("Connecting....");
            Connection conn= DriverManager.getConnection("jdbc:oracle:thin:system/system@localhost:1521:XE","system","system");
            System.out.println("Connected successfully....");
            stmt = conn.createStatement();
           stmt1 = conn.createStatement();
        }
        catch(Exception e)
        {}
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("SEARCH BILL");

        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Client Name");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("BILL NO");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("DETAILS OF SERVICES");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account Writing Charges", "Audit Fees", "Certification Charges", "Company Audit Fess", "Consultancy Fees", "Cost Audit Fees", "Exempt from ST: Appeals and Representation", "Exempt from ST: Others", "Exempt from ST: Servise Exported", "Exempt from ST: Service to Foreign Diplomatic Missions", "Exempt from ST: Service to SEZ and SEZ Developers", "Exempt from ST: Service to UN & International Agencies", "Fees for Reviewing Financial Accounts", "GST Return Filing Fees", "Income Tax Return Filing Fees", "Internal Audit Fees", "Limited Review Fees", "Management Services Fees", "Others", "Out of Pocket Expenses", "Project Report Charges", "Service Tax Return Filing Fees", "Statutory Audit Fees", "System Audit Fees", "Tax Audit Fees", "TDS Return Filing Fees", "VAT Audit Fees", "VAT Return Filing Fees" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton6.setText("SEARCH");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setText("DATE");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton7.setText("SEARCH");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BILL NO", "CLIENT NAME", "BILL DATE", "GST NO", "PAN NO", "DETAIL OF SERVICES", "PARTICULARS", "AMOUNT", "BILL PREFIX", "NAME NO SIGNATORY", "CLIENT PHONE NO", "CLIENT ADDRESSl"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable2);

        jButton8.setText("CLEAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(jButton8)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Search().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new lOGoUT().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        c_name=jTextField2.getText();
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jTextField2ActionPerformed(evt);
           String s = "SELECT b.bill_no,c.c_name,b.date1,c.gst_no,c.pan_no,b.details_of_service,b.particulars,b.amount,b.bill_pre,b.name,c.c_phone,c.c_addr from bill  b , client  c where b.c_name =c.c_name";
        //String s1;
        System.out.println(s);
        try {
            ResultSet rs1 = stmt.executeQuery(s);
            System.out.println("query executed");
            while(rs1.next()) {
                bill_no = rs1.getString(1);
                c_name = rs1.getString(2);
               date1= rs1.getString(3);
                gst_no = rs1.getString(4);
                pan_no=rs1.getString(5);
                
                details_of_services=rs1.getString(6);
                particulars=rs1.getString(7);
                amount=rs1.getString(8);
                bill_pre=rs1.getString(9);
                name=rs1.getString(10);
                c_phone=rs1.getString(11);
                c_addr=rs1.getString(12);
                
                
                //     while (rs.next())
                //  {

                    //  ArrayList row = new ArrayList(4);

                    //    for (int i = 1; i <= 4; i++)
                    //    {
                        //        row.add( rs.getObject(i) );
                        //    }

                    //    data.add( row );
                    //       }

                Object[] row = { bill_no,c_name,date1,gst_no,pan_no,details_of_services,particulars,amount,bill_pre,name,c_phone,c_addr };
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

                model.addRow(row);
                // JTable.setdata, columnNames);

            // String s = cust_id+"\t"+fname+"\t"+lname+"\t"+city+"\t"+pincode+"\t"+phone1+"\t"+phone2+"\t"+trans_id+"\t";
            //  jTextArea1.append(s+"\n");
        }

        } catch(Exception e) {
            System.out.println("Exception = "+e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
          jTextField1ActionPerformed(evt);
          
          int bill_no1;
          bill_no1=Integer.parseInt(bill_no);
           String s = "SELECT bill_no,date1,details_of_service,particulars,amount,bill_pre,name,c_name from bill  where bill_no="+bill_no1;
           
            System.out.println(s);
        try {
            ResultSet rs1 = stmt.executeQuery(s);
            System.out.println("query executed");
            while(rs1.next()) {
                bill_no = rs1.getString(1);
                
               date1= rs1.getString(2);
                
                details_of_services=rs1.getString(3);
                particulars=rs1.getString(4);
                amount=rs1.getString(5);
                bill_pre=rs1.getString(6);
                name=rs1.getString(7);
                c_name=rs1.getString(8);
                
                 String s1="select c_name,gst_no,pan_no,c_phone,c_addr from client where c_name='"+c_name+"'";
          
          
          
          try
          {
              ResultSet rs2 = stmt1.executeQuery(s1);
            System.out.println("query executed");
            while(rs2.next()) {
                 c_name = rs2.getString(1);
                gst_no = rs2.getString(2);
                pan_no= rs2.getString(3);
                c_phone = rs2.getString(4);
                c_addr=rs2.getString(5);
            }
            
                Object[] row = { bill_no,c_name,date1,gst_no,pan_no,details_of_services,particulars,amount,bill_pre,name,c_phone,c_addr };
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

                model.addRow(row);
          }
          catch(Exception e) {
            System.out.println("Exception = "+e);
        }
                //     while (rs.next())
                //  {

                    //  ArrayList row = new ArrayList(4);

                    //    for (int i = 1; i <= 4; i++)
                    //    {
                        //        row.add( rs.getObject(i) );
                        //    }

                    //    data.add( row );
                    //       }

                // JTable.setdata, columnNames);

            // String s = cust_id+"\t"+fname+"\t"+lname+"\t"+city+"\t"+pincode+"\t"+phone1+"\t"+phone2+"\t"+trans_id+"\t";
            //  jTextArea1.append(s+"\n");
        }

        } catch(Exception e) {
            System.out.println("Exception = "+e);
        }
        
        
           
         
          
          
          
         //  String s = "SELECT bill_no,date1,details_of_service,particulars,amount,bill_pre,name from bill  where c_name ='"+c_name+"' ";
        //String s1;
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        details_of_services=(String)jComboBox1.getSelectedItem();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
          
         jComboBox1ActionPerformed(evt);
          
         // int bill_no1;
        //  bill_no1=Integer.parseInt(bill_no);
           String s = "SELECT bill_no,date1,details_of_service,particulars,amount,bill_pre,name,c_name from bill  where details_of_service='"+details_of_services+"'";
           
            System.out.println(s);
        try {
            ResultSet rs1 = stmt.executeQuery(s);
            System.out.println("query executed");
            while(rs1.next()) {
                bill_no = rs1.getString(1);
                
               date1= rs1.getString(2);
                
                details_of_services=rs1.getString(3);
                particulars=rs1.getString(4);
                amount=rs1.getString(5);
                bill_pre=rs1.getString(6);
                name=rs1.getString(7);
                c_name=rs1.getString(8);
                
                 String s1="select c_name,gst_no,pan_no,c_phone,c_addr from client where c_name='"+c_name+"'";
          
          
          
          try
          {
              ResultSet rs2 = stmt1.executeQuery(s1);
            System.out.println("query executed");
            while(rs2.next()) {
                 c_name = rs2.getString(1);
                gst_no = rs2.getString(2);
                pan_no= rs2.getString(3);
                c_phone = rs2.getString(4);
                c_addr=rs2.getString(5);
            }
          }
          catch(Exception e) {
            System.out.println("Exception = "+e);
        }
                //     while (rs.next())
                //  {

                    //  ArrayList row = new ArrayList(4);

                    //    for (int i = 1; i <= 4; i++)
                    //    {
                        //        row.add( rs.getObject(i) );
                        //    }

                    //    data.add( row );
                    //       }

                Object[] row = { bill_no,c_name,date1,gst_no,pan_no,details_of_services,particulars,amount,bill_pre,name,c_phone,c_addr };
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

                model.addRow(row);
                // JTable.setdata, columnNames);

            // String s = cust_id+"\t"+fname+"\t"+lname+"\t"+city+"\t"+pincode+"\t"+phone1+"\t"+phone2+"\t"+trans_id+"\t";
            //  jTextArea1.append(s+"\n");
        }

        } catch(Exception e) {
            System.out.println("Exception = "+e);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        
         jTextField3ActionPerformed(evt);
          
         // int bill_no1;
        //  bill_no1=Integer.parseInt(bill_no);
           String s = "SELECT bill_no,date1,details_of_service,particulars,amount,bill_pre,name,c_name from bill  where date1='"+date1+"'";
           
            System.out.println(s);
        try {
            ResultSet rs1 = stmt.executeQuery(s);
            System.out.println("query executed");
            while(rs1.next()) {
                bill_no = rs1.getString(1);
                
               date1= rs1.getString(2);
                
                details_of_services=rs1.getString(3);
                particulars=rs1.getString(4);
                amount=rs1.getString(5);
                bill_pre=rs1.getString(6);
                name=rs1.getString(7);
                c_name=rs1.getString(8);
                
                 String s1="select c_name,gst_no,pan_no,c_phone,c_addr from client where c_name='"+c_name+"'";
          
          
          
          try
          {
              ResultSet rs2 = stmt1.executeQuery(s1);
            System.out.println("query executed");
            while(rs2.next()) {
                 c_name = rs2.getString(1);
                gst_no = rs2.getString(2);
                pan_no= rs2.getString(3);
                c_phone = rs2.getString(4);
                c_addr=rs2.getString(5);
            }
          }
          catch(Exception e) {
            System.out.println("Exception = "+e);
        }
                //     while (rs.next())
                //  {

                    //  ArrayList row = new ArrayList(4);

                    //    for (int i = 1; i <= 4; i++)
                    //    {
                        //        row.add( rs.getObject(i) );
                        //    }

                    //    data.add( row );
                    //       }

                Object[] row = { bill_no,c_name,date1,gst_no,pan_no,details_of_services,particulars,amount,bill_pre,name,c_phone,c_addr };
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

                model.addRow(row);
                // JTable.setdata, columnNames);

            // String s = cust_id+"\t"+fname+"\t"+lname+"\t"+city+"\t"+pincode+"\t"+phone1+"\t"+phone2+"\t"+trans_id+"\t";
            //  jTextArea1.append(s+"\n");
        }

        } catch(Exception e) {
            System.out.println("Exception = "+e);
        }
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        bill_no=jTextField1.getText();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
        date1=jTextField3.getText();
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
      //  jTable2.setModel(new DefaultTableModel());
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                        model.setRowCount(0); 
       // jTable2.setModel(modelo);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
